<?php

namespace App\Providers;

class RestaurantNameProvider extends \Faker\Provider\Base
{
    protected static $restaurantNames = [
        "McDonald's",
        "Wendy's",
        "Frisch's Big Boy",
        "OMG! Rotisserie",
        "Domino's Pizza",
        "Pizza Hut",
        "SONIC Drive In",
        "Long John Silver's",
        "Taco Bell",
        "Qdoba Mexican Grill",
        "Sonic Drive-In",
        "Taco John's",
        "Whataburger",
        "Hamburger King",
        "Burger King",
        "McDonalds",
        "Taco Time",
        "Jimmy John's",
        "Jersey Mike's Subs",
        "Popeyes Louisiana Kitchen",
        "Hardee's",
        "Rally's",
        "Quiznos",
        "Jack in the Box",
        "Subway",
        "Mr Hero",
        "Amigos/Kings Classic",
        "Raising Cane's Chicken Fingers",
        "Coop DeVille",
        "B. Good",
        "Back Yard Burgers",
        "Arby's",
        "Pacific Rim",
        "Panda Express",
        "Chick-fil-A",
        "Captain D's",
        "Samurai Sam's",
        "Northeastern State University",
        "Sarku Japan",
        "Five Guys",
        "Pei Wei",
        "Krystal",
        "Baja Fresh",
        "Bojangles' Famous Chicken 'n Biscuits",
        "Pollo Tropical",
        "Waffle House",
        "Popeye's Chicken & Biscuits",
        "Jimmy Johns",
        "Checkers",
        "Integrated Therapy Specialists: Arnold D Larson",
        "KFC",
        "Dairy Queen",
        "Penguin Point",
        "Goodcents Deli Fresh Subs",
        "White Castle",
        "Culver's",
        "Church's Chicken",
        "KFC / Taco Bell",
        "Jacks Grocery",
        "Chipotle Mexican Grill",
        "SUBWAY®",
        "Ernie's All American Burger",
        "Windmill Gourmet Fast Foods",
        "b.good",
        "Boston Market",
        "Dunkin Donuts",
        "Moe's Original Bar B Que",
        "Penn Station East Coast Subs",
        "Carl's Jr.",
        "Cook Out",
        "In-N-Out Burger",
        "Mr. Hero",
        "Del Taco",
        "Nick's Burgers",
        "Baker's Drive Thru",
        "Mc Donald's",
        "Mickey's Gyros & Ribs",
        "Long John Silvers",
        "Sensenig Poultry LLC",
        "Frugals",
        "Seaside Eatery",
        "Fazoli's",
        "Dunkin' Donuts",
        "Wetzel's Pretzels",
        "Ryan's",
        "Steak 'n Shake",
        "Granny's Drive-In",
        "Jolly's Drive-In",
        "Blondies",
        "Great Steak",
        "Sonic",
        "Rallys",
        "Lee's Famous Recipe Chicken",
        "Little Caesars Pizza",
        "Dairy Freeze",
        "QDOBA Mexican Eats",
        "Lime Ricky World",
        "Taco Mayo",
        "A&W/Long John Silvers",
        "Pick Up Stix",
        "Dairy Cheer",
        "Fallguys Burger Company",
        "Golden Chick",
        "McLaren's Pantry",
        "Red Robin Gourmet Burgers",
        "Buds Chicken & Seafood",
        "Sconecutter",
        "Zip's Hamburgers And Fish",
        "Rush's",
        "El Pollo Loco",
        "Carl's Jr",
        "Gold Star Chili",
        "Moe's Southwest Grill",
        "Popeyes Chicken and Biscuits",
        "Dominos Pizza",
        "Pizza Barn",
        "Taco Casa",
        "Taco Bueno",
        "Tom's Drive In",
        "Tudor's Biscuit World",
        "Kasa's Pizza",
        "Skyline Chili",
        "Dewey's Pizza",
        "Custard Hut & Pizza",
        "Papa John's Pizza",
        "TacoTime",
        "Blakes Lotaburger",
        "Panera Bread",
        "Cook-Out",
        "George's Gyros Spot",
        "Hardees",
        "El Paragua Restaurant",
        "Captain D's Seafood",
        "Burger Time",
        "Chicken Express",
        "KFC - Kentucky Fried Chicken",
        "Cherry Hill Drive In Ice Cream",
        "Flip Burger Bar",
        "Greyhound",
        "Noodles & Company",
        "Pal's Sudden Service",
        "Arctic Circle",
        "Bob Evans",
        "Don & Millie's",
        "Old Country Buffet",
        "Tommy's Sub Shop",
        "Roy Rogers",
        "BIG & little's Restaurant",
        "Cafe Rio",
        "Char-Grill",
        "Crispy Chicken & Seafood",
        "Toppers Pizza",
        "Topper's Pizza",
        "Lion's Choice",
        "Popeyes Chicken & Biscuits",
        "Kum & Go",
        "Taco Delight",
        "Kenny's Drive-In",
        "Pita Pit",
        "MOOYAH Burgers, Fries & Shakes",
        "The Pita Pit",
        "Slim Chickens",
        "Shot Tower Inn",
        "Blake's LotaBurger",
        "Handy's Lunch",
        "Meatheads",
        "A&W Restaurant",
        "Jack Pirtles Chicken",
        "Wendys",
        "Dairy Isle",
        "Hardee's / Red Burrito",
        "Runza",
        "Shoney's on the Go",
        "Richie's Restaurant",
        "Yellow Cab Pizza Co.",
        "Jack's",
        "Rally's Hamburgers",
        "Popeye's Louisiana Kitchen",
        "Rancher's Roast Beef Inc.",
        "Pizza Factory",
        "In-A-Tub",
        "Crystal Restaurant",
        "Burger's Landing",
        "Isabella's Pizzeria",
        "Fatburger",
        "Sunrise Cafe",
        "Round Table Pizza",
        "Capt Crab's Take-Away",
        "Papa Johns Pizza",
        "Ben & Jerry's",
        "Auntie Anne's",
        "Baskin-Robbins",
        "31st Avenue Gyro",
        "Au Bon Pain",
        "Saladworks",
        "Baja Fresh Mexican Grill",
        "Papa Johns",
        "Good Times Burgers & Frozen Custard",
        "Johnny Rockets",
        "Wingstop",
        "Luby's",
        "Mayfair Boardwalk Grill",
        "Nino's Pizza",
        "Maria's Fry Bread & Mexican Food",
        "Papa John's",
        "Taco Del Mar",
        "Wingstreet",
        "Charleys Philly Steaks",
        "Papa John’s Pizza",
        "Nick's Gyros",
        "South-A-Philly Steaks and Hoagies",
        "DQ Grill & Chill / Orange Julius",
        "Lenny's Sub Shop",
        "Popeye's",
        "Taco Local",
        "Stars Drive-In",
        "Firehouse Subs",
        "Original Tracks",
        "Thrasher's French Fries",
        "Subway Citgo of Quarryville",
        "Fuku",
        "Capriotti's Sandwich Shop",
        "Eldon Drive In",
        "Petro's Chili & Chips",
        "The Halal Guys",
        "Ny Chicken Fish",
        "Thunder Ridge Ampride",
        "Twisters",
        "Cookout",
        "Tasty Carryout",
        "Hub City Express",
        "Culvers",
        "Shloma Inc",
        "Bravo Tacos",
        "Papagus Gyros",
        "DQ Grill & Chill",
        "Taqueria",
        "A & W Family Restaurant",
        "Los Verdes",
        "Taco Cabana",
        "Bad Daddys Burger Bar",
        "AJ's Hotdogs & Gyros",
        "Rubio's Coastal Grill",
        "Papa Gino's",
        "Cusinera",
        "St Louis Original Hamburgers",
        "Circle Drive In",
        "Woody's Sloppy Dogs",
        "Kum Go",
        "Mc Donalds",
        "JCW's",
        "The People Connection",
        "Hot Dog Heaven",
        "The Great Steak & Potato Co.",
        "Jim's Coney Island",
        "Charcoal Delights",
        "Sheetz",
        "McDonalds @ Old Atlanta",
        "Hungry Andy's",
        "Port Of Subs",
        "Carls Jr",
        "Hot Dog On A Stick",
        "Carl's / Green Burrito",
        "Wu's Fine Chinese Cuisine",
        "KFC/Taco Bell",
        "Steak-out",
        "Wings N' More Wings",
        "P. Terry's",
        "J J Fish and Chicken",
        "A&W",
        "Kentucky Fried Chicken",
        "Greek Oven Pizza and Wings",
        "Wienerschnitzel",
        "City Bites",
        "Smoothie King",
        "Bobby's Burger Palace",
        "Smashburger",
        "Hometown Buffet",
        "Dairy Queen Grill & Chill",
        "The Biscuit Factory",
        "Subway (johnson) @ Jonesboro",
        "China King",
        "Popeyes",
        "Stripes Store #2276",
        "Hotdoks",
        "A&W All-American Food",
        "Shepard's Drive-In",
        "McDonald's of Mililani Mauka",
        "Mariu Kebabberia Gastronomica",
        "Tropical Smoothie Cafe",
        "Fred's Store",
        "Bamboo Bistro",
        "Raising Cane's",
        "LocoL",
        "Quick",
        "Backyard Burgers",
        "Jim Bob's Chicken Fingers",
        "Islands Restaurant",
        "Charlie's Chicken",
        "Famous Dave's",
        "Dawg House Grill",
        "Carl's Jr - Green Burrito",
        "Carls Jr. / Green Burrito",
        "Jimmy John's Gourmet Sandwiches",
        "The Agora",
        "Cody's Cafe",
        "Mcdonald's - Walmart",
        "Mcalister's Deli",
        "Bb&t",
        "Flash Foods / McDonald's",
        "Carl's Jr. / Green Burrito",
        "B Z Breakfast Burgers Beyond",
        "Farmer Boys",
        "Milo's Hamburgers",
        "Wings And Philly",
        "A&W All American Food",
        "Nathan's Famous",
        "Gianni's Pizza",
        "Rich's Mighty Fine Burgers Grub",
        "Bob Evans Restaurant",
        "Spangles",
        "Chuck Wagon",
        "Chicken House",
        "Dino's Gyros",
        "Jamjam",
        "Fab Wings N Burgers",
        "Pizza One",
        "The Chicken Place",
        "Chick-fil-a Superstition Springs Center",
        "Pollo Campero",
        "Rahway Chicken & Burger Inc",
        "Sbarro",
        "The Pizza Pipe Line",
        "Omega Drive-In",
        "China Buddha Inn II",
        "Geno's Fast Break",
        "Jersey Jacks Eatery",
        "Hardee's / Red Burrito / Dough Boys",
        "Kettle Restaurant",
        "Hoka Hoka Bento",
        "Iceberg Drive Inn",
        "Regal Cinemas Tikahtnu  16 IMAX & RPX",
        "Mario's Natural Roman Pizza",
        "Music City Subs",
        "Chick-fil-a Orange Avenue",
        "Gyros Kings",
        "McDonald’s",
        "Einstein Bros Bagels",
        "Blimpie",
        "A&W All-American Foods",
        "Sammy Carry-Out",
        "Redbox",
        "Little Caesar's Pizza Smithfield",
        "Checkers Burgers and Fries",
        "Kerby's Koney Island",
        "L&l Hawaiian Barbecue",
        "Braum's Ice Cream & Dairy Store",
        "Tellers Tap Room & Kitchen",
        "Arby's Antigo",
        "Furr's",
        "Subway Sandwiches and Salads",
        "Bills Place",
        "Burger King Salou",
        "ShopRite",
        "Wendy Two Two Eight",
        "Braum's",
        "Boston Market 381",
        "Great Steak & Potato Co",
        "Blimpie Subs & Sandwiches",
        "Checker's",
        "Mr Char-Burger",
        "Yum Brands Inc",
        "Ama Ristorante",
        "Popeye's Chicken",
        "The Honeybaked Ham Company",
        "Snack Shack",
        "Boston Chowda Company",
        "Long John Silver's / A&W",
        "Aprisa Mexican Cuisine",
        "Steak N Shake",
        "White Manna Hamburgers",
        "Food 4 Less",
        "Starbucks",
        "Brixton's",
        "Dairy Queen - Round Rock",
        "Peking Wok",
        "Panda",
        "Pop-A-Nugget",
        "Roly Poly",
        "KFC / A&W",
        "Thrashers French Fries",
        "Subway - Roland Park",
        "Garden Catering",
        "Foster's Freeze",
        "Rapid Ray's",
        "Portillo's",
        "Vista Drive In",
        "Arbys",
        "Tom's Grill",
        "Yoshinoya",
        "Subway - Bell's Ferry",
        "Pizza Hut Wingstreet",
        "Travelcenters of America",
        "D'Angelo Grilled Sandwiches",
        "Fitness 19",
        "Royal Buffet",
        "Cousins Subs",
        "Lanesplitter Pizza & Pub",
        "World Wrapps",
        "Hunam Garden",
        "Soulfish Grill",
        "Kam's Chop Suey",
        "Ziti's Italian Express",
        "Rally's Springfield",
        "Subway Sandwiches",
        "Home Town Buffet",
        "Checker's Drive-in Restaurant",
        "Grandy's",
        "Ll Hawaiian Barbecue",
        "Maui Tacos",
        "Checker's Hamburgers",
        "Carl's Jr / Green Burrito",
        "Frugal's",
        "Rafael's",
        "Crown Fried Chicken",
        "Garden Fast Food",
        "Froots",
        "Luxor Food Court",
        "Spangle's",
        "Subway Guitars",
        "Love's",
        "Cypress Best",
        "Siam To Go",
        "Bush's Chicken",
        "Chick-fil-a Truett's Luau",
        "Strongwater Spirits & Botanicals",
        "The Break Away Sports Cafe",
        "Charley's Grilled Subs",
        "Mcdonald's #25557",
        "Rocky's",
        "Chester's Grill",
        "44872",
        "Zaxby's",
        "Osgood's",
        "Dan's Seafood & Chicken",
        "Jason's Deli",
        "Breadeaux Pizza",
        "Sonic Drive-in (trailer)",
        "Aw Restaurant",
        "Steak Escape",
        "7-Eleven",
        "Jollibee",
        "Kennedy Fried Chicken & Pizza",
        "Mocha Express",
        "Taco Bell/Pizza Hut Express",
        "Schlotzsky's",
        "Charlie Browns",
        "Ball State Lafollette Dining",
        "Tubby's Grilled Submarines",
        "Quizno's +",
        "Long John Silvers / A&W",
        "Comilao Lanches Bakery",
        "Gabby's Burgers & Fries",
        "Loco Moco Drive-Inn",
        "Pizza Express",
        "Alice's",
        "King Grill",
        "Freddy's Steakburger",
        "Cousins Subs of Green Bay - Oneida St. & Ramada Way",
        "Everest",
        "Jamba Juice",
        "Quiznos Sub",
        "Exxon",
        "BGR - The Burger Joint",
        "Chick-fil-a Magnolia Mall",
        "Tom & Jerry's",
        "Ivar's Seafood Bar",
        "Luna Corner Pizza",
        "Fosters Freeze",
        "Scoopers",
        "Eagan's Drive-In",
        "Omelette House",
        "Hermosa",
        "Costa Vida Fresh Mexican Grill",
        "Simmies Arirang Hill Cheese Steak",
        "Chris' Drive-In",
        "The Flame Broiler",
        "DQ Woodlands",
        "Rubio's",
        "Burgerville",
        "Lukes on Harlem",
        "Madison Street Subs",
        "Fresh City",
        "Denton's",
        "Teddy's Bigger Burgers",
        "Dairy Queen Grill & Chill / Orange Julius",
        "Elevation Burger",
        "Your Healthy Habit",
        "Mazatlan Mexican Restaurant",
        "Kim Lee Fast Food",
        "Cinnabon",
        "China King Restaurant",
        "Chickenow",
        "Chicago Union Station Food Court",
        "Paesano's",
        "B K",
        "Pizza Primetime",
        "Convergence Zone",
        "The Press Club",
        "Costa Vida",
        "Hegenburgers",
        "Pete's Burgers",
        "Dual - Carls / Grn Burrito 1100654",
        "Kings Contrivance Jewelers",
        "Great Steak And Potato Co",
        "Nielsen's Frozen Custard",
        "Tina's Carryout Restaurant",
        "Long John Silver/ A&W",
        "Car's Late Night Delivery",
        "Charkies",
        "El Tarasco Mexican Food",
        "Burgerville, USA",
        "Italian Pizzeria Restaurant",
        "Lee's Oriental Martial Arts",


    ];

    public function restaurantName()
    {
        return static::randomElement(static::$restaurantNames);
    }


    protected static $foodNames = array(
        'Pizza au fromage', 'Hamburger', 'Cheeseburger', 'Moules Marinières', 'Salade Grecque',
        'Petit Hamburger', 'Petit Cheeseburger', 'Petit Bacon Burger', 'Petit Bacon Cheeseburger',
        'Sandwich Vegan', 'Sandwich Vegan au fromage', 'Fromage grillé', 'Pates',
        'Cheese Dog', 'Hot Dog', 'Welsh', 'Tartiflette', 'Boeuf Bourguignons'
    );

    protected static $beverageNames = array(
        'Bière', 'Bourgeon Léger', 'Miller Lite', 'Thé Froid',
        'Milk Shake', 'Thé', 'Café', 'Thé chaud', 'Chocolat Chaud',
        'Champagne', 'Vin', 'Limonade', 'Coca-Cola', 'Oasis',
        'Eau', 'Sprite', 'Jus d\'Orange', 'Café frappé'
    );

    protected static $dairyNames = array(
        'Beurre',
        'Lait',
        'Fromage',
        'Mozzarella',
        'Yaourt',
        'Crème',
    );

    protected static $vegetableNames = array(
        'Oignon',
        'Ail',
        'Tomate',
        'Pomme de terre',
        'Carotte',
        'Poivron',
        'Basil',
        'Persil',
        'Brocoli',
        'Blé',
        'Épinard',
        'Champignon',
        'Gingembre',
        'Chilie',
        'Romarin',
        'Concombre',
        'Cornichon',
        'Avocat',
        'Citrouille',
        'Menthe',
        'Aubergine',
        'Poireau'
    );

    protected static $fruitNames = array(
        'Citron',
        'Pomme',
        'Banane',
        'Fraise',
        'Orange',
        'Ananas',
        'Myrtille',
        'Raisin',
        'Noix de coco',
        'Framboise',
        'Mangue',
        'Poire',
        'Mûre',
        'Cerise',
        'Pastèque',
        'Melon',
        'Kiwi',
        'Papaye',
        'Goyave',
        'Litchi'
    );

    protected static $meatNames = array(
        'Poulet',
        'Bacon',
        'Saucisse',
        'Boeuf',
        'Jambon',
        'Porc',
        'Dinde',
        'Paupiette',
    );

    protected static $sauceNames = array(
        'Sauce tomate',
        'Concentré de tomate',
        'Mayonaise',
        'Sauce barbecue',
        'Ketchup'
    );

    /**
     * A random Food Name.
     * @return string
     */
    public function foodName()
    {
        return static::randomElement(static::$foodNames);
    }

    /**
     * A random Beverage Name.
     * @return string
     */
    public function beverageName()
    {
        return static::randomElement(static::$beverageNames);
    }

    /**
     * A random Dairy Name.
     * @return string
     */
    public function dairyName()
    {
        return static::randomElement(static::$dairyNames);
    }

    /**
     * A random Vegetable Name.
     * @return string
     */
    public function vegetableName()
    {
        return static::randomElement(static::$vegetableNames);
    }

    /**
     * A random Fruit Name.
     * @return string
     */
    public function fruitName()
    {
        return static::randomElement(static::$fruitNames);
    }

    /**
     * A random Meat Name.
     * @return string
     */
    public function meatName()
    {
        return static::randomElement(static::$meatNames);
    }

    /**
     * A random Sauce Name.
     * @return string
     */
    public function sauceName()
    {
        return static::randomElement(static::$sauceNames);
    }
}

